#!/bin/bash
TOP=$(realpath "$(dirname "${BASH_SOURCE[0]}")"/..)
source "$TOP/scripts/funcs.sh"

cmd="$1"
shift
case "$cmd" in
	(info)
		echo "$(pkg-info)"
		;;
	(build)
		echo "$(pkgbuild "$1")"
		;;
	(runit-gitea-list)
		echo "$(runit-gitea-list)"
		;;
	(runit-gitea-clone)
		rm -rf "$TOP/gitea"
		mkdir "$TOP/gitea"
		for x in $(runit-gitea-list);do
			git clone "https://gitea.artixlinux.org/packages/$x.git"
		done
		;;
	(*)
		echo "!!!!! usage $(basename "$0") [info|build|]"
		exit 1
		;;
esac
