#!/usr/bin/env python
html_format='''<!DOCTYPE html>
<html>
<head>
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
 <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
 <title>Downloads</title>
 <style type="text/css">
  BODY { font-family : monospace, sans-serif;  color: black;}
  P { font-family : monospace, sans-serif; color: black; margin:0px; padding: 0px;}
  A:visited { text-decoration : none; margin : 0px; padding : 0px;}
  A:link    { text-decoration : none; margin : 0px; padding : 0px;}
  A:hover   { text-decoration: underline; background-color : yellow; margin : 0px; padding : 0px;}
  A:active  { margin : 0px; padding : 0px;}
  /*table, th, td {
    border: 1px solid black;
    }*/
  th, td { text-align: right; }
  th:nth-child(1) { text-align: left; }
  td:nth-child(1) { text-align: left; }
  th {
    cursor: pointer;
	}
 </style>
<script>
function setup(){
$('th').click(function(){
    var table = $(this).parents('table').eq(0)
    var rows = table.find('tr:gt(0)').toArray().sort(comparer($(this).index()))
    this.asc = !this.asc
    if (!this.asc){rows = rows.reverse()}
    for (var i = 0; i < rows.length; i++){table.append(rows[i])}
})
}
function comparer(index) {
    return function(a, b) {
        var valA = getCellValue(a, index), valB = getCellValue(b, index)
        return $.isNumeric(valA) && $.isNumeric(valB) ? valA - valB : valA.toString().localeCompare(valB)
    }
}
function getCellValue(row, index){ return $(row).children('td').eq(index).text() }
</script>
</head>
<body onload="setup()">
	%s
	<table>
	<tr><th>Name</th><th>Size</th><th>Date</th></tr>
	%s
	</table>
</body>
</html>'''
		
def main():
	import sys, os, stat
	from datetime import datetime, timezone
	prog = os.path.basename(sys.argv[0])
	def usage(msg=None):
		print(f'Usage: use {prog} <foldername>')
		if msg: print(msg)
		sys.exit(-1)

	def index(d,n=0):
		if not os.path.isdir(d):
			usage(f"argument '{d}' is not a directory")
		E = os.listdir(d)
		L = []
		for e in E:
			if e=='index.html': continue
			p = os.path.join(d,e)
			if os.path.isdir(p):
				index(p,n+1)
				s = 0	#sort low
			else:
				s = 1
			mode = os.stat(p)
			size = str(mode[stat.ST_SIZE])
			mt = datetime.fromtimestamp(mode[stat.ST_MTIME],timezone.utc).strftime('%Y%m%dU%H%M%S')
			L.append((s,e,size,mt))
		L.sort()
		rows = '\n'.join([f'<tr><td><a href="./{e[1]}">{e[1]}&nbsp;</a></td><td>&nbsp;{e[2]}</td><td>&nbsp;{e[3]}</td></tr>'
					for e in L])
		#rows = '\n'.join([f'<tr><td><a href="./{e[1]}">{e[1]}{(C["name"]+1-len(e[1]))*"&nbsp;"}</a></td><td>{(C["size"]+1-len(e[2]))*"&nbsp;"}{e[2]}</td><td>{(C["mt"]+1-len(e[3]))*"&nbsp;"}{e[3]}</td></tr>'
		#			for e in L])
		back = '<a href="../">..</a><br/><br/>' if n else ''
		with open(os.path.join(d,'index.html'),'w') as f:
			f.write(html_format % (back,rows))

	if len(sys.argv)==2:
		index(sys.argv[1])
	else:
		usage()
if __name__=='__main__':
	main()
