#!/usr/bin/env python
html_format='''<!DOCTYPE html>
<html>
<head>
 <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
 <title>Downloads</title>
 <style type="text/css">
  BODY { font-family : monospace, sans-serif;  color: black;}
  P { font-family : monospace, sans-serif; color: black; margin:0px; padding: 0px;}
  A:visited { text-decoration : none; margin : 0px; padding : 0px;}
  A:link    { text-decoration : none; margin : 0px; padding : 0px;}
  A:hover   { text-decoration: underline; background-color : yellow; margin : 0px; padding : 0px;}
  A:active  { margin : 0px; padding : 0px;}
 </style>
</head>
<body>
	%s
	%s
</body>
</html>'''
		
def main():
	import sys, os, stat
	from datetime import datetime, timezone
	prog = os.path.basename(sys.argv[0])
	def usage(msg=None):
		print(f'Usage: use {prog} <foldername>')
		if msg: print(msg)
		sys.exit(-1)

	def index(d,n=0):
		if not os.path.isdir(d):
			usage(f"argument '{d}' is not a directory")
		E = os.listdir(d)
		L = []
		C = dict(name=0,size=0,mt=0)
		for e in E:
			if e=='index.html': continue
			p = os.path.join(d,e)
			if os.path.isdir(p):
				index(p,n+1)
				s = 0	#sort low
			else:
				s = 1
			mode = os.stat(p)
			C['name'] = max(C['name'],len(e))
			size = str(mode[stat.ST_SIZE])
			C['size'] = max(C['size'],len(size))
			mt = datetime.fromtimestamp(mode[stat.ST_MTIME],timezone.utc).strftime('%Y%m%dU%H%M%S')
			C['mt'] = max(C['mt'],len(mt))
			L.append((s,e,size,mt))
		L.sort()
		rows = '<br/>\n'.join([f'<a href="./{e[1]}">{e[1]}{(C["name"]+1-len(e[1]))*"&nbsp;"}</a>{(C["size"]+1-len(e[2]))*"&nbsp;"}{e[2]}{(C["mt"]+1-len(e[3]))*"&nbsp;"}{e[3]}'
					for e in L])
		back = '<a href="../">..</a><br/>' if n else ''
		with open(os.path.join(d,'index.html'),'w') as f:
			f.write(html_format % (back,rows))

	if len(sys.argv)==2:
		index(sys.argv[1])
	else:
		usage()
if __name__=='__main__':
	main()
