#!/bin/bash
set -e
TOP=$(realpath "$(dirname "${BASH_SOURCE[0]}")"/..)
tmp="$TOP/tmp"
[ ! -d "$tmp" ] && mkdir pp "$tmp" || true
exec |& tee "$tmp/make-one.log"
#source ${TOP}/scripts/funcs.sh
prog="$(basename "$0")"
src="$1"
if [ ! -d "$src" -o ! -f "$src/PKGBUILD" ]; then
	echo "!!!!! Usage: $prog <dir> $src should contain PKGBUILD" 
	exit 1
fi
src="$(realpath "$src")"
build="$tmp/build-one"
rm -rf "$build"
cp -pr "$src" "$build"
htdocs="${htdocs:-"$TOP/htdocs"}"
repo="${repo:-"$htdocs/nitro-world"}"
dbname="$(basename "$repo")"
for a in x86_64 aarch64;do
	pkgs="$repo/$a"
	[ ! -d "$pkgs" ] && mkdir -p "$pkgs" || true
done

#hacking signage
export GPG_TTY=$(tty)
gpg-connect-agent updatestartuptty /bye >/dev/null
MAKEPKGOPTS=${MAKEPKGOPTS:-'--nodeps --sign'}

for x in "$build"/PKGBUILD; do
	[ ! -f "$x" ] && echo "!!!!! '$x' is not a file" && continue
	d="$(dirname "$x")" 
	rm  -rf "$d"/{src,pkg,*.zst,*.zst.sig,.SRCINFO}
	(
	cd "$d"
	if updpkgsums; then
		if makepkg --printsrcinfo > .SRCINFO; then
			if makepkg ${MAKEPKGOPTS}; then
				echo "##### $prog: makepkg made $(ls *.zst)"
				for p in *.zst; do
					case "$p" in
						(*-any.pkg.tar.zst)
							pkgs="$repo/x86_64"
							;;
						(*-x86_64.pkg.tar.zst)
							pkgs="$repo/x86_64"
							;;
						(*-aarch64.pkg.tar.zst)
							pkgs="$repo/aarch64"
							;;
						(*)
							echo "!!!!! unknown arch: '$p'"
							continue
							;;
					esac
					if [ ! -e "$pkgs/$p" ]; then
						if [ -z "$DRYRUN" ]; then
							mv "$p" "$p.sig" "$pkgs/"
							case "$p" in
								(*-any.pkg.tar.zst)
									x86_64="$repo/x86_64/$p"
									aarch64="$repo/aarch64/$p"
									cp "$pkgs/$p"{,.sig} "$repo/aarch64/"
									;;
								(*-x86_64.pkg.tar.zst)
									x86_64="$repo/x86_64/$p"
									;;
								(*-aarch64.pkg.tar.zst)
									aarch64="$repo/aarch64/$p"
									;;
							esac
							[ -n "$x86_64" ] && repo-add -R -s $repo/x86_64/$dbname.db.tar.zst "$x86_64"
							[ -n "$aarch64" ] && repo-add -R -s $repo/aarch64/$dbname.db.tar.zst "$aarch64"
						fi
					else
						echo "!!!!! $prog: '$pkgs/$p' already exists"
						exit 2
					fi
				done
				cp -pr "$build/PKGBUILD" "$src"
			else
				echo "!!!!! $prog: makepkg failed" 1>&2
			fi
		else
			echo "!!!!! $prog: makepkg --printsrcinfo failed" 1>&2
		fi
	else
		echo "!!!!! $prog: updpkgsums failed" 1>&2
	fi
	)
done
"$TOP/scripts/indexer" "$htdocs"
