#!/bin/bash
TOP=$(realpath "$(dirname "${BASH_SOURCE[0]}")"/..)
PROG="$(basename "$0")"
source "$TOP/scripts/funcs.sh"
DIR="$1"
KIND="$2"
[ -z "$KIND" -o ! -d "$DIR" ] && echo "!!!!! usage $PROG <giteatop> <pkgbuildvarname>" && exit 1
deps=()
for d in "$DIR"/*/PKGBUILD; do
	eval A=\("$(pkgbuild-value "$d" "$KIND")"\)
	for x in "${A[@]}"; do
		if [ -n "$FILTER" ]; then
			x="$(depends-filter "$x")"
		fi
		[ -n "$x" ] && echo "'$x'" || true
	done
done | sort -u
