#!/bin/bash
set -e
TOP=$(realpath "$(dirname "${BASH_SOURCE[0]}")"/..)
tmp="$TOP/tmp"
[ ! -d "$tmp" ] && mkdir pp "$tmp" || true
exec |& tee "$tmp/resign.log"
prog="$(basename "$0")"
htdocs="${htdocs:-"$TOP/htdocs"}"
repo="${repo:-"$htdocs/nitro-world"}"
dbname="$(basename "$repo")"
rm -f $(find "$repo" -name "$dbname".db\*)
rm -f $(find "$repo" -name "$dbname".files\*)
rm -f $(find "$repo" -name \*.sig)
rm -f $(find "$repo" -name \*.html)
rm -f $(find "$repo" -name \*.old)
rm -f $(find "$repo" -name \*.old.\*)

#hacking signage
export GPG_TTY=$(tty)
gpg-connect-agent updatestartuptty /bye >/dev/null

for arepo in "$repo"/*; do
	X="$(find "$arepo" -type f)"
	[ -z "$X" ] && continue
	for x in ${X}; do
		gpg --output "$x.sig" --detach-sig "$x"
		touch -r "$x" "$x.sig"
	done
	repo-add -R -s $arepo/$dbname.db.tar.zst ${X}
done
"$TOP/scripts/indexer" "$htdocs"
